# Generated by Django 5.2.8 on 2025-11-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('genre', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_player_1', to='users.user', verbose_name='')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_of_player_2', to='users.user', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('local', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('enrollment', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('n_players', models.SmallIntegerField()),
                ('categories', models.ManyToManyField(to='cambeach_app.category')),
            ],
        ),
    ]
