# Generated by Django 5.2.8 on 2025-11-14 13:33

import cambeach_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('genre', models.SmallIntegerField(verbose_name=cambeach_app.models.Gender)),
            ],
        ),
    ]
