# Generated by Django 5.2.8 on 2025-11-25 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')])),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('n_players', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Dupla')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado')], default='P', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cambeach_app.category')),
                ('players', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cambeach_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cambeach_app.category')),
                ('teams', models.ManyToManyField(related_name='groups', to='cambeach_app.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cambeach_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('score_team_a', models.SmallIntegerField(blank=True, null=True)),
                ('score_team_b', models.SmallIntegerField(blank=True, null=True)),
                ('round', models.CharField(choices=[('G', 'Fase de Grupos'), ('O', 'Oitavas de Final'), ('Q', 'Quartas de Final'), ('S', 'Semifinal'), ('F', 'Final')], default='G', max_length=1)),
                ('category_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cambeach_app.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_in_group', to='cambeach_app.group')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='cambeach_app.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='cambeach_app.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cambeach_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_teams', models.SmallIntegerField(default=16, verbose_name='Maximo de duplas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='cambeach_app.category')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='cambeach_app.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='categories',
            field=models.ManyToManyField(related_name='tournaments', through='cambeach_app.TournamentDivision', to='cambeach_app.category'),
        ),
    ]
