# Generated by Django 5.2.8 on 2025-11-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')]),
        ),
    ]
