# Generated by Django 5.2.8 on 2025-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0002_alter_category_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
