# Generated by Django 5.2.8 on 2025-11-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0005_tournament_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='categories',
            field=models.ManyToManyField(related_name='tournaments', to='cambeach_app.category'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cambeach_app.category')),
                ('players', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='cambeach_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('score_team_a', models.SmallIntegerField(blank=True, null=True)),
                ('score_team_b', models.SmallIntegerField(blank=True, null=True)),
                ('category_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cambeach_app.category')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cambeach_app.tournament')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='cambeach_app.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='cambeach_app.team')),
            ],
        ),
    ]
