# Generated by Django 5.2.8 on 2025-11-20 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0006_remove_tournament_user_alter_tournament_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Dupla'),
        ),
        migrations.CreateModel(
            name='TournamentDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_teams', models.SmallIntegerField(default=16, verbose_name='Maximo de duplas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='cambeach_app.category')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='cambeach_app.tournament')),
            ],
        ),
    ]
