# Generated by Django 5.2.8 on 2025-11-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0007_alter_team_name_tournamentdivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='categories',
        ),
    ]
