# Generated by Django 5.2.8 on 2025-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0008_remove_tournament_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='categories',
            field=models.ManyToManyField(related_name='tournaments', through='cambeach_app.TournamentDivision', to='cambeach_app.category'),
        ),
    ]
