# Generated by Django 5.2.8 on 2025-11-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('concluida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('urgencia', models.CharField(choices=[('PEQUENA', 'Pequena'), ('MEDIA', 'Média'), ('GRANDE', 'Grande')], default='pequena', max_length=7)),
            ],
        ),
    ]
