# Generated by Django 5.2.8 on 2025-11-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambeach_app', '0003_alter_category_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='categoria_de_jogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cambeach_app.category'),
        ),
    ]
