# Generated by Django 5.2.8 on 2025-11-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_atleta_categoria_de_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='genero',
        ),
    ]
