# Generated by Django 5.2.8 on 2025-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_atleta_categoria_remove_atleta_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
