# Generated by Django 5.2.8 on 2025-11-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_atleta_genero'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='atleta',
            managers=[
            ],
        ),
    ]
