# Generated by Django 5.2.8 on 2025-11-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_atleta_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='genero',
        ),
    ]
